Simple_Word2Vec:
  compile_params:
    loss: categorical_crossentropy
    metrics:
    - accuracy
    - f1
    optimizer: adam
  embedding_dim: 100
  model_layers:
  - !!python/object:keras.src.layers.core.embedding.Embedding
    _activity_regularizer: null
    _auto_config: &id001 !!python/object:keras.src.saving.serialization_lib.Config
      config:
        input_dim: 10000
        output_dim: 100
        trainable: false
    _auto_get_config: true
    _auto_track_sub_layers: true
    _autocast: false
    _batch_input_shape: !!python/tuple
    - null
    - null
    _build_input_shape: null
    _call_spec: !!python/object:keras.src.utils.layer_utils.CallFunctionSpec
      _arg_names:
      - inputs
      _default_training_arg: null
      _expects_mask_arg: false
      _expects_training_arg: false
      _full_argspec: !!python/object/new:inspect.FullArgSpec
      - - self
        - inputs
      - null
      - null
      - null
      - []
      - null
      - {}
    _callable_losses: []
    _captured_weight_regularizer: []
    _compute_dtype_object: &id003 !!python/object/apply:tensorflow.python.framework.dtypes.as_dtype
    - float32
    _dtype_policy: !!python/object:keras.src.mixed_precision.policy.Policy
      _compute_dtype: float32
      _name: float32
      _variable_dtype: float32
    _dynamic: false
    _inbound_nodes_value: []
    _initial_weights: null
    _input_spec: null
    _instrumented_keras_api: true
    _instrumented_keras_layer_class: true
    _instrumented_keras_model_class: false
    _losses: []
    _metrics: []
    _name: embedding_1
    _name_scope_on_declaration: ''
    _non_trainable_weights: []
    _obj_reference_counts_dict: !!python/object/new:keras.src.utils.object_identity.ObjectIdentityDictionary
      state: !!python/tuple
      - null
      - _storage:
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: false
          : 4
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: 100
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: 10000
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: *id001
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: &id002 !!python/object:keras.src.initializers.initializers.RandomUniform
                _random_generator: !!python/object:keras.src.backend.RandomGenerator
                  _built: false
                  _rng_type: stateless
                  _seed: null
                maxval: 0.05
                minval: -0.05
                seed: null
          : 1
    _outbound_nodes_value: []
    _preserve_input_structure_in_config: false
    _saved_model_arg_spec: null
    _saved_model_inputs_spec: null
    _self_setattr_tracking: true
    _self_tracked_trackables: []
    _stateful: false
    _supports_masking: false
    _trainable: false
    _trainable_weights: []
    _updates: []
    _use_one_hot_matmul: false
    built: false
    embeddings_constraint: null
    embeddings_initializer: *id002
    embeddings_regularizer: null
    input_dim: 10000
    input_length: null
    mask_zero: false
    output_dim: 100
    sparse: false
  - !!python/object:keras.src.layers.reshaping.flatten.Flatten
    _activity_regularizer: null
    _auto_config: &id004 !!python/object:keras.src.saving.serialization_lib.Config
      config: {}
    _auto_get_config: true
    _auto_track_sub_layers: true
    _autocast: true
    _build_input_shape: null
    _call_spec: !!python/object:keras.src.utils.layer_utils.CallFunctionSpec
      _arg_names:
      - inputs
      _default_training_arg: null
      _expects_mask_arg: false
      _expects_training_arg: false
      _full_argspec: !!python/object/new:inspect.FullArgSpec
      - - self
        - inputs
      - null
      - null
      - null
      - []
      - null
      - {}
    _callable_losses: []
    _captured_weight_regularizer: []
    _channels_first: false
    _compute_dtype_object: *id003
    _dtype_policy: !!python/object:keras.src.mixed_precision.policy.Policy
      _compute_dtype: float32
      _name: float32
      _variable_dtype: float32
    _dynamic: false
    _inbound_nodes_value: []
    _initial_weights: null
    _input_spec: !!python/object:keras.src.engine.input_spec.InputSpec
      allow_last_axis_squeeze: false
      axes: {}
      dtype: null
      max_ndim: null
      min_ndim: 1
      name: null
      ndim: null
      shape: null
    _instrumented_keras_api: true
    _instrumented_keras_layer_class: true
    _instrumented_keras_model_class: false
    _losses: []
    _metrics: []
    _name: flatten_1
    _name_scope_on_declaration: ''
    _non_trainable_weights: []
    _obj_reference_counts_dict: !!python/object/new:keras.src.utils.object_identity.ObjectIdentityDictionary
      state: !!python/tuple
      - null
      - _storage:
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: false
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: true
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: *id004
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: channels_last
          : 1
    _outbound_nodes_value: []
    _preserve_input_structure_in_config: false
    _saved_model_arg_spec: null
    _saved_model_inputs_spec: null
    _self_setattr_tracking: true
    _self_tracked_trackables: []
    _stateful: false
    _supports_masking: false
    _trainable: true
    _trainable_weights: []
    _updates: []
    built: false
    data_format: channels_last
  - !!python/object:keras.src.layers.core.dense.Dense
    _activity_regularizer: null
    _auto_config: &id005 !!python/object:keras.src.saving.serialization_lib.Config
      config:
        activation: relu
        units: 128
    _auto_get_config: true
    _auto_track_sub_layers: true
    _autocast: true
    _build_input_shape: null
    _call_spec: !!python/object:keras.src.utils.layer_utils.CallFunctionSpec
      _arg_names:
      - inputs
      _default_training_arg: null
      _expects_mask_arg: false
      _expects_training_arg: false
      _full_argspec: !!python/object/new:inspect.FullArgSpec
      - - self
        - inputs
      - null
      - null
      - null
      - []
      - null
      - {}
    _callable_losses: []
    _captured_weight_regularizer: []
    _compute_dtype_object: *id003
    _dtype_policy: !!python/object:keras.src.mixed_precision.policy.Policy
      _compute_dtype: float32
      _name: float32
      _variable_dtype: float32
    _dynamic: false
    _inbound_nodes_value: []
    _initial_weights: null
    _input_spec: !!python/object:keras.src.engine.input_spec.InputSpec
      allow_last_axis_squeeze: false
      axes: {}
      dtype: null
      max_ndim: null
      min_ndim: 2
      name: null
      ndim: null
      shape: null
    _instrumented_keras_api: true
    _instrumented_keras_layer_class: true
    _instrumented_keras_model_class: false
    _losses: []
    _metrics: []
    _name: dense_2
    _name_scope_on_declaration: ''
    _non_trainable_weights: []
    _obj_reference_counts_dict: !!python/object/new:keras.src.utils.object_identity.ObjectIdentityDictionary
      state: !!python/tuple
      - null
      - _storage:
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: true
          : 3
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: 128
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: &id007 !!python/object:keras.src.initializers.initializers.Zeros {}
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: *id005
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: &id006 !!python/name:keras.src.activations.relu ''
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: &id008 !!python/object:keras.src.initializers.initializers.GlorotUniform
                _random_generator: !!python/object:keras.src.backend.RandomGenerator
                  _built: false
                  _rng_type: stateless
                  _seed: null
                distribution: uniform
                mode: fan_avg
                scale: 1.0
                seed: null
          : 1
    _outbound_nodes_value: []
    _preserve_input_structure_in_config: false
    _saved_model_arg_spec: null
    _saved_model_inputs_spec: null
    _self_setattr_tracking: true
    _self_tracked_trackables: []
    _stateful: false
    _supports_masking: true
    _trainable: true
    _trainable_weights: []
    _updates: []
    activation: *id006
    bias_constraint: null
    bias_initializer: *id007
    bias_regularizer: null
    built: false
    kernel_constraint: null
    kernel_initializer: *id008
    kernel_regularizer: null
    units: 128
    use_bias: true
  - !!python/object:keras.src.layers.core.dense.Dense
    _activity_regularizer: null
    _auto_config: &id009 !!python/object:keras.src.saving.serialization_lib.Config
      config:
        activation: softmax
        units: 6
    _auto_get_config: true
    _auto_track_sub_layers: true
    _autocast: true
    _build_input_shape: null
    _call_spec: !!python/object:keras.src.utils.layer_utils.CallFunctionSpec
      _arg_names:
      - inputs
      _default_training_arg: null
      _expects_mask_arg: false
      _expects_training_arg: false
      _full_argspec: !!python/object/new:inspect.FullArgSpec
      - - self
        - inputs
      - null
      - null
      - null
      - []
      - null
      - {}
    _callable_losses: []
    _captured_weight_regularizer: []
    _compute_dtype_object: *id003
    _dtype_policy: !!python/object:keras.src.mixed_precision.policy.Policy
      _compute_dtype: float32
      _name: float32
      _variable_dtype: float32
    _dynamic: false
    _inbound_nodes_value: []
    _initial_weights: null
    _input_spec: !!python/object:keras.src.engine.input_spec.InputSpec
      allow_last_axis_squeeze: false
      axes: {}
      dtype: null
      max_ndim: null
      min_ndim: 2
      name: null
      ndim: null
      shape: null
    _instrumented_keras_api: true
    _instrumented_keras_layer_class: true
    _instrumented_keras_model_class: false
    _losses: []
    _metrics: []
    _name: dense_3
    _name_scope_on_declaration: ''
    _non_trainable_weights: []
    _obj_reference_counts_dict: !!python/object/new:keras.src.utils.object_identity.ObjectIdentityDictionary
      state: !!python/tuple
      - null
      - _storage:
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: true
          : 3
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: 6
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: &id011 !!python/object:keras.src.initializers.initializers.Zeros {}
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: &id012 !!python/object:keras.src.initializers.initializers.GlorotUniform
                _random_generator: !!python/object:keras.src.backend.RandomGenerator
                  _built: false
                  _rng_type: stateless
                  _seed: null
                distribution: uniform
                mode: fan_avg
                scale: 1.0
                seed: null
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: *id009
          : 1
          ? !!python/object/new:keras.src.utils.object_identity._ObjectIdentityWrapper
            state: !!python/tuple
            - null
            - _wrapped: &id010 !!python/name:keras.src.activations.softmax ''
          : 1
    _outbound_nodes_value: []
    _preserve_input_structure_in_config: false
    _saved_model_arg_spec: null
    _saved_model_inputs_spec: null
    _self_setattr_tracking: true
    _self_tracked_trackables: []
    _stateful: false
    _supports_masking: true
    _trainable: true
    _trainable_weights: []
    _updates: []
    activation: *id010
    bias_constraint: null
    bias_initializer: *id011
    bias_regularizer: null
    built: false
    kernel_constraint: null
    kernel_initializer: *id012
    kernel_regularizer: null
    units: 6
    use_bias: true
  trainable: false
  vocab_size: 10000
